parameters:
    container.dumper.inline_factories: true

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    Roromix\Bundle\SpreadsheetBundle\Factory: '@phpspreadsheet'
    PouyaSoft\SDateBundle\Service\jDateService: '@pouya_soft.j_sdate_service'
    GuzzleHttp\Client: '@eight_points_guzzle.client.my_client'

    templating:
        alias: Twig\Environment
        public: true

    PouyaSoft\AppzaBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Kernel.php'
            - '../../Tests/'

    PouyaSoft\AppzaBundle\Services\SMS:
        arguments:
            $smsConfig: '%sms_config%'
            $env: '%kernel.environment%'

#    PouyaSoft\AppzaBundle\Services\Pdf:
#        arguments:
#            $cacheDir: '%kernel.cache_dir%/pdf'
#            $webDir: '%kernel.project_dir%/public'