services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            Roromix\Bundle\SpreadsheetBundle\Factory: '@phpspreadsheet'
            PouyaSoft\SDateBundle\Service\jDateService: '@pouya_soft.j_sdate_service'
            GuzzleHttp\Client: '@eight_points_guzzle.client.my_client'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    PouyaSoft\AppzaBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
#    PouyaSoft\AppzaBundle\Controller\:
#        resource: '../../Controller/'
#        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # explicitly configure the service
    PouyaSoft\AppzaBundle\Services\SMS:
        arguments:
            $sms_enabled: '%sms_enabled%'

    PouyaSoft\AppzaBundle\Services\Pdf:
        arguments:
            $cacheDir: '%kernel.cache_dir%/pdf'
            $webDir: '%kernel.project_dir%/public'