stages:
    - test
    - deploy

test:
    stage: test
    image: phpwatch/docker-php:latest
    before_script:
        - php -v
        - composer install --prefer-dist -q --no-progress
    script:
        - ./vendor/bin/phpunit -v --coverage-text --colors=never --stderr

deploy_composer:
    only:
        - tags
    stage: deploy
    script:
        - curl -sS --show-error --fail --data tag=${CI_COMMIT_TAG} "https://Appza:t29GHY4022000RU04t5y4gh2347y924@gitlab.com/api/v4/projects/22583819/packages/composer"